package com.stage.pfe.persistance;

// Generated 5 févr. 2015 15:31:46 by Hibernate Tools 3.4.0.CR1

/**
 * Ville generated by hbm2java
 */
public class Ville implements java.io.Serializable {

	private Integer idville;
	private String nomVille;

	public Ville() {
	}

	public Ville(String nomVille) {
		this.nomVille = nomVille;
	}

	public Integer getIdville() {
		return this.idville;
	}

	public void setIdville(Integer idville) {
		this.idville = idville;
	}

	public String getNomVille() {
		return this.nomVille;
	}

	public void setNomVille(String nomVille) {
		this.nomVille = nomVille;
	}

}
